name: Docker CI - Validación de compilación

on:
  push:
  pull_request:

jobs:
  docker-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validar Dockerfile con docker/build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          call: check

  docker-bake-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validar compilación con docker/bake
        uses: docker/bake-action@v6
        with:
          call: check